export function createTrade(fields) {
  return {
    ...fields,
    id: fields.id || Date.now() + Math.random().toString(),
    symbol: fields.symbol ? fields.symbol.trim().toUpperCase() : "",
    tradeType: fields.tradeType || "Spot",
    exchange: fields.exchange || "Binance",
    side: fields.side || "Long",
    entry: parseFloat(fields.entry) || 0,
    exit: fields.exit !== null && fields.exit !== undefined ? parseFloat(fields.exit) : null,
    qty: parseFloat(fields.qty) || 0,
    leverage: parseFloat(fields.leverage) || 1,
    pnl: parseFloat(fields.pnl) || 0,
    fees: parseFloat(fields.fees) || 0,
    openTime: fields.openTime || Date.now(),
    closeTime: fields.closeTime || null,
    setup: fields.setup || "Other",
    mistake: fields.mistake || "None",
    closeReason: fields.closeReason || "Other",
    notes: fields.notes || "",
    status: fields.status || (fields.exit ? "closed" : "live"),
    stopLoss: fields.stopLoss ? parseFloat(fields.stopLoss) : null,
    takeProfit: fields.takeProfit ? parseFloat(fields.takeProfit) : null,
    quoteCurrency: fields.quoteCurrency || "USDT",
    usdtRate: fields.usdtRate || 1,
    entryType: fields.entryType || null,
    profileId: fields.profileId || "default",
  };
}
